In [32]:
from sklearn.datasets import fetch_olivetti_faces
X, y = fetch_olivetti_faces(return_X_y=True)
X.shape, y.shape

((400, 4096), (400,))

In [33]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((300, 4096), (100, 4096), (300,), (100,))

In [34]:
from sklearn.neighbors import KNeighborsClassifier

modelo1 = KNeighborsClassifier()
modelo1.fit(X_train, y_train)
knn_predict = modelo1.predict(X_test)
knn_hits = knn_predict == y_test
knn_hits, sum(knn_hits)/len(knn_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True, False, False,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.83)

In [35]:
from sklearn.naive_bayes import GaussianNB

modelo2 = GaussianNB()
modelo2.fit(X_train, y_train)
gauss_predict = modelo2.predict(X_test)
gauss_hits = gauss_predict == y_test
gauss_hits, sum(gauss_hits)/len(gauss_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True, False,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
        False]),
 0.81)

In [36]:
from sklearn.linear_model import Perceptron

modelo3 = Perceptron()
modelo3.fit(X_train, y_train)
perceptron_predict = modelo3.predict(X_test)
perceptron_hits = perceptron_predict == y_test
perceptron_hits, sum(perceptron_hits)/len(perceptron_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True, False,  True, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True, False,  True,  True,
        False]),
 0.78)

In [37]:
import numpy as np
hits = np.stack((knn_hits, gauss_hits, perceptron_hits))


In [41]:
y_predict  = np.stack((knn_predict, gauss_predict, perceptron_predict))

In [42]:
from scipy import stats
y_predict = stats.mode(y_predict)[0][0]
vo_hists = y_predict == y_test
vo_hists, sum(vo_hists)/len(vo_hists)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.91)

# Combinação de classificadores



In [51]:
from sklearn.ensemble import VotingClassifier
modelo = VotingClassifier({
    ('knn', KNeighborsClassifier()),
    ('naivebayes', GaussianNB()),
    ('perceptron', Perceptron())
})
modelo.fit(X_train, y_train)
vote_predict = modelo.predict(X_test)
vote_hits = vote_predict == y_test
vote_hits, sum(vote_hits)/len(vote_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.91)

In [52]:
from sklearn.tree import DecisionTreeClassifier
modelo = VotingClassifier({
    ('knn', KNeighborsClassifier()),
    ('naivebayes', GaussianNB()),
    ('perceptron', Perceptron()),
    ('tree', DecisionTreeClassifier())
})
modelo.fit(X_train, y_train)
vote_predict = modelo.predict(X_test)
vote_hits = vote_predict == y_test
vote_hits, sum(vote_hits)/len(vote_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.89)

# Diversificação por reamostragem


In [55]:
from sklearn.ensemble import BaggingClassifier

modelo = BaggingClassifier(DecisionTreeClassifier(), random_state=42)
modelo.fit(X_train, y_train)
bag_predict = modelo.predict(X_test)
bag_hits = bag_predict == y_test
bag_hits, sum(bag_hits)/len(bag_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False,  True,  True, False,  True, False, False,  True,
         True,  True, False,  True, False, False,  True, False,  True,
         True,  True,  True, False,  True,  True,  True, False, False,
        False,  True, False, False, False,  True, False,  True, False,
         True,  True,  True,  True, False, False,  True,  True, False,
         True, False, False, False,  True,  True,  True,  True, False,
        False,  True, False,  True, False,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True, False,  True,
        False]),
 0.64)

In [ ]:
# Aumentando a aleatoriedade para aumentar a diversidade

In [56]:
from sklearn.ensemble import BaggingClassifier

modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), random_state=42)
modelo.fit(X_train, y_train)
bag_predict = modelo.predict(X_test)
bag_hits = bag_predict == y_test
bag_hits, sum(bag_hits)/len(bag_hits)

(array([ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False, False,  True,
         True,  True,  True, False,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True, False,  True, False,  True,  True,
        False,  True,  True, False,  True, False,  True,  True, False,
         True, False, False,  True, False,  True,  True,  True, False,
        False,  True, False,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True]),
 0.72)

In [57]:
from sklearn.ensemble import BaggingClassifier

modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)
bag_predict = modelo.predict(X_test)
bag_hits = bag_predict == y_test
bag_hits, sum(bag_hits)/len(bag_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.89)

# Random Forest é um baggin de Árvore de Decisão


In [60]:
from sklearn.ensemble import RandomForestClassifier

modelo = RandomForestClassifier(random_state=42)
modelo.fit(X_train, y_train)
bag_predict = modelo.predict(X_test)
bag_hits = bag_predict == y_test
bag_hits, sum(bag_hits)/len(bag_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.88)

# Regularização do Bagging

In [61]:
from sklearn.ensemble import BaggingClassifier

modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), n_estimators=100, random_state=42, max_features=0.15)
modelo.fit(X_train, y_train)
bag_predict = modelo.predict(X_test)
bag_hits = bag_predict == y_test
bag_hits, sum(bag_hits)/len(bag_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.94)

# Florestas extremamente aleatórias

In [62]:
from sklearn.ensemble import ExtraTreesClassifier

modelo = ExtraTreesClassifier(random_state=42)
modelo.fit(X_train, y_train)
bag_predict = modelo.predict(X_test)
bag_hits = bag_predict == y_test
bag_hits, sum(bag_hits)/len(bag_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

# Boosting


In [65]:
from sklearn.ensemble import AdaBoostClassifier

modelo = AdaBoostClassifier(DecisionTreeClassifier(max_depth=25, splitter='random'), learning_rate=0.15, random_state=42)
modelo.fit(X_train, y_train)
bag_predict = modelo.predict(X_test)
bag_hits = bag_predict == y_test
bag_hits, sum(bag_hits)/len(bag_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True, False,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.92)

In [ ]:
from xgboost import X

modelo = AdaBoostClassifier(DecisionTreeClassifier(max_depth=25, splitter='random'), learning_rate=0.15, random_state=42)
modelo.fit(X_train, y_train)
bag_predict = modelo.predict(X_test)
bag_hits = bag_predict == y_test
bag_hits, sum(bag_hits)/len(bag_hits)

In [66]:
import warnings
warnings.filterwarnings('ignore')


In [69]:
from sklearn.ensemble import StackingClassifier

voting = VotingClassifier({
    ('knn', KNeighborsClassifier()),
    ('naivebayes', GaussianNB()),
    ('perceptron', Perceptron()),
    ('tree', DecisionTreeClassifier())
})

modelo = StackingClassifier([
    ('voting', voting),
    ('extretrees', ExtraTreesClassifier(random_state=42)),
    ('randomForest', RandomForestClassifier(random_state=42))
], cv=3, passthrough=True)


modelo.fit(X_train, y_train)
vote_predict = modelo.predict(X_test)
vote_hits = vote_predict == y_test
vote_hits, sum(vote_hits)/len(vote_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True]),
 0.92)

In [70]:
from sklearn.ensemble import StackingClassifier

modelo = StackingClassifier([
    ('randomForest', RandomForestClassifier(random_state=42)),
    ('randomForest43', RandomForestClassifier(random_state=43)),
    ('randomForest44', RandomForestClassifier(random_state=44)),
], cv=3, passthrough=True)


modelo.fit(X_train, y_train)
vote_predict = modelo.predict(X_test)
vote_hits = vote_predict == y_test
vote_hits, sum(vote_hits)/len(vote_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)