In [10]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target
X.shape, y.shape



((442, 10), (442,))

In [11]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer, mean_squared_error
import numpy as np

modelo = KNeighborsRegressor(9)
scores  = cross_validate(modelo, X, y, scoring=make_scorer(mean_squared_error, greater_is_better=False, squared=False))
print(scores['test_score'])
sempad = np.mean(scores['test_score'])
print(f"sem pradronização {sempad}")


[-56.19003238 -59.32108614 -59.00744094 -54.78238886 -57.37903883]
sem pradronização -57.3359974298196


In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
params = {
    'n_neighbors':[3,5,7]
}

modelo = GridSearchCV(KNeighborsRegressor(), params, scoring=make_scorer(mean_squared_error, greater_is_better=False, squared=False))
modelo.fit(X, y)
modelo.best_estimator_

KNeighborsRegressor(n_neighbors=7)

In [13]:
from sklearn.metrics import make_scorer, mean_squared_error
from math import sqrt

ypred = modelo.predict(X)
mse = mean_squared_error(y, ypred)
sqrt(mse)

51.15149901888715

In [14]:
scores  = cross_validate(modelo, X, y, scoring=make_scorer(mean_squared_error, greater_is_better=False, squared=False))
print(scores['test_score'])
sempad = np.mean(scores['test_score'])
print(f"sem pradronização {sempad}")

[-56.99180879 -62.93518794 -59.57483095 -55.63774296 -60.43146504]
sem pradronização -59.114207135103996


In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
params = {
    'n_neighbors':[3,5,7]
}

grid_knn = GridSearchCV(KNeighborsRegressor(), params, scoring='neg_mean_squared_error')

modelo = Pipeline([
    ('padronizacao', StandardScaler()),
    ('gsknn', grid_knn)
])

scores  = cross_validate(modelo, X, y, scoring=make_scorer(mean_squared_error, greater_is_better=False, squared=False))
print(scores['test_score'])
compad = np.mean(scores['test_score'])
print(f"com pradronização {compad}")

[-56.82092904 -63.05450375 -60.15515846 -54.92728369 -59.33477082]
com pradronização -58.858529150715086


In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor

pipeline = Pipeline([
    ('padronizacao', StandardScaler()),
    ('knn', KNeighborsRegressor())
])

params = {
    'knn__n_neighbors':[3,5,7]
}
modelo = GridSearchCV(pipeline, params, scoring='neg_mean_squared_error')


scores  = cross_validate(modelo, X, y, scoring=make_scorer(mean_squared_error, greater_is_better=False, squared=False))
print(scores['test_score'])
compad = np.mean(scores['test_score'])
print(f"com pradronização {compad}")

[-56.82092904 -63.05450375 -60.15515846 -54.92728369 -59.33477082]
com pradronização -58.858529150715086
